name: Build macOS Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install required packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka==1.8.6
          pip install pillow requests Py3AMF==0.8.10 curl_cffi==0.10.0

      # Step 4: Build the executable with Nuitka
      - name: Build with Nuitka
        run: |
          python -m nuitka --onefile --standalone --no-pyi-file --remove-output \
            --include-module=verification \
            --include-module=scfarm \
            --include-module=room \
            --include-module=profile_picture \
            --include-module=msp \
            --include-module=login_helper \
            --include-module=idretriever \
            --include-module=draftdesign \
            --include-module=autograph \
            --include-module=ascii \
            --include-module=animation \
            --include-module=curl_cffi.requests \
            --include-module=Py3AMF \
            --include-module=Py3AMF.amf0 \
            --include-module=Py3AMF.amf3 \
            --include-package=PIL \
            --include-module=tkinter \
            --include-module=tkinter.scrolledtext \
            --include-module=tkinter.messagebox \
            --enable-plugin=tk-inter \
            --macos-icon-from-icns=assets/icon.icns \
            main-gui.py

      # Step 5: Make the binary executable
      - name: Make .bin executable
        run: |
          chmod +x main-gui.bin

      # Step 6: Upload the executable as an artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-gui-macos
          path: main-gui.bin
