name: Build macOS Executable

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - main   # change if you use a different default branch

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pillow requests py3amf

      - name: Build with Nuitka
        run: |
          nuitka \
            --onefile \
            --standalone \
            --no-pyi-file \
            --no-debug-immortal-assumptions \
            --remove-output \
            --include-module=verification \
            --include-module=scfarm \
            --include-module=room \
            --include-module=profile_picture \
            --include-module=msp \
            --include-module=login_helper \
            --include-module=idretriever \
            --include-module=draftdesign \
            --include-module=autograph \
            --include-module=ascii \
            --include-module=animation \
            --include-module=requests \
            --include-package=PIL \
            --include-module=tkinter \
            --include-module=tkinter.scrolledtext \
            --include-module=tkinter.messagebox \
            --include-module=pyamf \
            --include-module=pyamf.amf0 \
            --include-module=pyamf.amf3 \
            --enable-plugin=tk-inter \
            main-gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            main-gui.bin
            main-gui.dist/
