name: Build macOS Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka==1.8.6 pillow requests Py3AMF==0.8.10 curl_cffi==0.10.0

      - name: Build with Nuitka (sources in .github/workflows)
        run: |
          set -e
          cd .github/workflows
          mkdir -p dist
          python -m nuitka --onefile --standalone \
            --no-pyi-file \
            --remove-output \
            --include-module=verification \
            --include-module=scfarm \
            --include-module=room \
            --include-module=profile_picture \
            --include-module=msp \
            --include-module=login_helper \
            --include-module=idretriever \
            --include-module=draftdesign \
            --include-module=autograph \
            --include-module=ascii \
            --include-module=animation \
            --include-module=requests \
            --include-module=curl_cffi.requests \
            --include-module=pyamf \
            --include-module=pyamf.amf0 \
            --include-module=pyamf.amf3 \
            --include-package=PIL \
            --include-module=tkinter \
            --include-module=tkinter.scrolledtext \
            --include-module=tkinter.messagebox \
            --enable-plugin=tk-inter \
            --output-dir=dist \
            main-gui.py

      - name: Wrap built binary into .app bundle
        run: |
          set -e
          cd .github/workflows

          APP_NAME="StarKey"
          BUNDLE_DIR="$APP_NAME.app/Contents"
          mkdir -p "$BUNDLE_DIR/MacOS" "$BUNDLE_DIR/Resources"

          # Detect Nuitka onefile output
          BIN_CANDIDATE=""
          if [ -f "dist/main-gui.bin" ]; then
            BIN_CANDIDATE="dist/main-gui.bin"
          elif [ -f "dist/main-gui" ]; then
            BIN_CANDIDATE="dist/main-gui"
          else
            BIN_CANDIDATE=$(ls -1 dist | grep -i "main" | head -n 1 || true)
            if [ -n "$BIN_CANDIDATE" ]; then
              BIN_CANDIDATE="dist/$BIN_CANDIDATE"
            fi
          fi

          if [ -z "$BIN_CANDIDATE" ] || [ ! -f "$BIN_CANDIDATE" ]; then
            echo "ERROR: Could not find Nuitka output in dist/ (checked main-gui.bin and main-gui and others)."
            ls -la dist || true
            exit 1
          fi

          echo "Using binary: $BIN_CANDIDATE"
          cp "$BIN_CANDIDATE" "$BUNDLE_DIR/MacOS/main-gui"
          chmod +x "$BUNDLE_DIR/MacOS/main-gui"

          # Copy icon if present
          if [ -f "assets/icon.icns" ]; then
            cp "assets/icon.icns" "$BUNDLE_DIR/Resources/icon.icns"
          else
            echo "Warning: assets/icon.icns not found; bundle will have no icon."
          fi

          # Create Info.plist
          PLIST_PATH="$BUNDLE_DIR/Info.plist"
          echo '<?xml version="1.0" encoding="UTF-8"?>' > "$PLIST_PATH"
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$PLIST_PATH"
          echo '<plist version="1.0">' >> "$PLIST_PATH"
          echo '<dict>' >> "$PLIST_PATH"
          echo '  <key>CFBundleName</key>' >> "$PLIST_PATH"
          echo "  <string>$APP_NAME</string>" >> "$PLIST_PATH"
          echo '  <key>CFBundleDisplayName</key>' >> "$PLIST_PATH"
          echo "  <string>$APP_NAME</string>" >> "$PLIST_PATH"
          echo '  <key>CFBundleIdentifier</key>' >> "$PLIST_PATH"
          echo "  <string>com.yourname.$APP_NAME</string>" >> "$PLIST_PATH"
          echo '  <key>CFBundleVersion</key>' >> "$PLIST_PATH"
          echo '  <string>1.0</string>' >> "$PLIST_PATH"
          echo '  <key>CFBundleExecutable</key>' >> "$PLIST_PATH"
          echo '  <string>main-gui</string>' >> "$PLIST_PATH"
          echo '  <key>CFBundleIconFile</key>' >> "$PLIST_PATH"
          echo '  <string>icon.icns</string>' >> "$PLIST_PATH"
          echo '  <key>LSMinimumSystemVersion</key>' >> "$PLIST_PATH"
          echo '  <string>10.12</string>' >> "$PLIST_PATH"
          echo '  <key>LSApplicationCategoryType</key>' >> "$PLIST_PATH"
          echo '  <string>public.app-category.utilities</string>' >> "$PLIST_PATH"
          echo '</dict>' >> "$PLIST_PATH"
          echo '</plist>' >> "$PLIST_PATH"

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: StarKey-macos
          path: .github/workflows/StarKey.app
